<?php 
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Sso
 * @author    Webkul
 * @copyright Copyright (c) 2010-2016 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<a href="http://ramakantpandey.com/mage4/sso/sso/index?redirect_uri=http://webkul.akshay.com/Symfony/gitgud/symfony/uvdeskRefactor/web/app_dev.php/en/customer/login-oidc" id="Popup"><button id="ssoFormLogin">Click</button></a>
<script type="text/javascript">
require(
[
    'jquery',
    'mage/template',
    'Magento_Ui/js/modal/alert'
],function($, template,alert){
    $(document).ready(function() {
        $('#Popup').click(function() {
            // (function(){
            var NWin = window.open('http://ramakantpandey.com/mage4/sso/sso/index?redirect_uri=http://webkul.akshay.com/Symfony/gitgud/symfony/uvdeskRefactor/web/app_dev.php/en/customer/login-oidc&client_id=1d948138c2dcf17994fbe52bec5ce95e');
            if (window.focus){
            NWin.focus();
            }
            return false;
        });
            // })();
    });
});
</script>